---
galaxy_info:
  author: Team ITigres
  description: Installation de l'agent Pulse pour monitoring Docker et Kubernetes
  license: MIT-0
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
