- name: Créer le dossier Uptime Kuma
  ansible.builtin.file:
    path: /opt/Uptime_Kuma
    state: directory
    mode: '0755'

- name: Vérifier présence du docker compose dans /opt 
  ansible.builtin.stat:
    path: /opt/Uptime_Kuma/docker-compose.yml
  register: docker_compose_check

- name: Copier le docker-compose
  ansible.builtin.template:
    src: /Infra_GSBV2/Ansible/roles/Uptime_Kuma/templates/docker-compose.yml
    dest: /opt/Uptime_Kuma/docker-compose.yml
    remote_src: no
  when: not docker_compose_check.stat.exists 

- name: Lancer le docker-compose
  community.docker.docker_compose_v2:
    project_src: /opt/Uptime_Kuma
    state: present

- name: Restaurer la conf du Uptime Kuma
  ansible.builtin.copy:
    src: data/
    dest: /var/lib/docker/volumes/uptime_kuma_kuma_db/_data/
    mode: "0755" 
  notify: Redémarrer Uptime_Kuma
