---
# MariaDB Configuration
mariadb_version: "10.7"
mariadb_root_password: "StrongRootPassw0rd!"
mariadb_database: "glpi"
mariadb_user: "glpi_user"
mariadb_password: "GlpiUserPassw0rd!"
mariadb_container_name: "mariadb"

# GLPI Configuration
glpi_version: "11.0.4"
glpi_container_name: "glpi"
glpi_db_host: "mariadb"
glpi_db_name: "glpi"
glpi_db_user: "glpi_user"
glpi_db_password: "GlpiUserPassw0rd!"