all:
  children:
    linuxs:
      vars:
        ansible_python_interpreter: /usr/bin/python3
      hosts: 
        Adguard:
         ansible_host: 172.16.0.3
         ansible_user: root
         ansible_ssh_private_key_file: ~/etc/ansible/keys/Adguard
        Stack-Web:
         ansible_host: 172.16.0.4
         ansible_user: root
         ansible_ssh_private_key_file: ~/etc/ansible/keys/Stack-Web
        Stack-App: 
         ansible_host: 172.16.0.5
         ansible_user: root
         ansible_ssh_private_key_file: ~/etc/ansible/keys/Stack-App
        Dockermail: 
         ansible_host: 172.16.0.6
         ansible_user: root
         ansible_ssh_private_key_file: ~/etc/ansible/keys/Dockermail
        SFTPGO: 
         ansible_host: 172.16.69.2
         ansible_user: root
         ansible_ssh_private_key_file: ~/etc/ansible/keys/SFTPGO

    routeur:
      hosts:
        EdgeRouter:
          ansible_host: 172.16.0.254
          ansible_user: ubnt
          ansible_password: "Formation13@"
          ansible_connection: network_cli
          ansible_network_os: vyos

    switchs:
      hosts:
        Sw01:
          ansible_host: 10.10.0.3
          ansible_user: admin
          ansible_password: "Formation13@"
        Sw02:
          ansible_host: 10.10.0.4
          ansible_user: admin
          ansible_password: "Formation13@"

    winservers:
      hosts:
        WinSRV01:
          ansible_host: 172.16.0.1
          ansible_user: Administrateur
          ansible_password: "Formation13@"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
        WinSRV02:
          ansible_host: 172.16.0.2
          ansible_user: Administrateur
          ansible_password: "Formation13@"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore