all: 
  children: 
    linuxs:
      hosts: 
        Adguard:
         ansible_host: 172.16.0.3
         ansible_user: root
         ansible_ssh_private_key_file: /etc/ansible/keys/Adguard
        Uptime_Kuma:
         ansible_host: 172.16.0.4
         ansible_user: root
         ansible_ssh_private_key_file: /etc/ansible/keys/UptimeKuma
        GLPI: 
         ansible_host: 172.16.0.5
         ansible_user: root
         ansible_ssh_private_key_file: /etc/ansible/keys/GLPI

    routeur:
      hosts:
        EdgeRouter:
          ansible_host: 172.16.0.254
          ansible_user: ubnt
          ansible_password: "Formation13@"
          ansible_connection: network_cli
          ansible_network_os: vyos
    winservers:
      hosts:
        WinSRV01:
          ansible_host: 172.16.0.1
          ansible_user: Administrateur
          ansible_password: "Formation13@"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore
        WinSRV02:
          ansible_host: 172.16.0.2
          ansible_user: Administrateur
          ansible_password: "Formation13@"
          ansible_connection: winrm
          ansible_port: 5985
          ansible_winrm_transport: basic
          ansible_winrm_server_cert_validation: ignore