- name: Update 
  hosts: linuxs
  become: yes
  roles: 
    - roles/MAJ  

- name: Install Docker
  become: yes
  hosts: linuxs
  roles:
    - roles/Install_Docker

- name : Install AdGuard
  become: yes
  hosts: Adguard
  roles:
    - roles/Adguard

- name : Install Uptime Kuma
  become: yes
  hosts: Uptime_Kuma
  roles:
    - roles/Uptime_Kuma

- name : Install GLPI
  become: yes
  hosts: GLPI
  roles:
    - roles/GLPI

- name : Promouvoir l'AD
  hosts: WinSRV01
  roles:
    - roles/PromouvoirAD01

- name: ReplicationAD02
  hosts: WinSRV02
  roles:
    - roles/ReplicationAD02
